Resources:
    QueueConsumerRole:
        Type: AWS::IAM::Role
        Properties:
            Path: /
            RoleName: ${self:custom.resourceName}_queue_consumer_role
            AssumeRolePolicyDocument:
                Version: "2012-10-17"
                Statement:
                    - Effect: Allow
                      Principal:
                          Service:
                              - lambda.amazonaws.com
                      Action: sts:AssumeRole
            ManagedPolicyArns:
                - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
            Policies:
                - PolicyName: ${self:custom.resourceName}_queue_consumer
                  PolicyDocument:
                      Version: "2012-10-17"
                      Statement:
                          # allow DynamoDB updates
                          - Effect: Allow
                            Action:
                                - dynamodb:UpdateItem
                            Resource:
                                - !GetAtt Table.Arn
                          # allow SQS consumer actions
                          - Effect: Allow
                            Action:
                                - sqs:DeleteMessage
                                - sqs:GetQueueAttributes
                                - sqs:ReceiveMessage
                            Resource:
                                - !GetAtt Queue.Arn
                            #
                          - Effect: Allow
                            Action:
                                - logs:CreateLogGroup
                                - logs:CreateLogStream
                                - logs:PutLogEvents
                            Resource: "*"
                            # xray
                          - Effect: Allow
                            Action:
                                - xray:PutTelemetryRecords
                                - xray:PutTraceSegments
                            Resource: "*"
