version: 0.2

phases:
    install:
        runtime-versions:
            nodejs: latest
        commands:
            - npm --prefix frontend/ install
    pre_build:
        commands:
            - echo "create .env file"
            - cat > .env.prod << EOF
            - UserPoolId = "$UserPoolId"
            - UserPoolWebClientId = "$UserPoolWebClientId"
            - IdentityPool = "$IdentityPool"
            - HttpApiUrl = "$HttpApiUrl"
            - EOF
    build:
        commands:
            - cat .env.prod
            - npm --prefix frontend/ run build
    post_build:
        commands:
            - echo "sync S3 bucket"
            - aws s3 sync --acl public-read ./frontend/build s3://$FrontendBucket
            - aws cloudfront create-invalidation --distribution-id $CloudFrontDistribution --paths '/index.html'
