version: 0.2

phases:
    install:
        runtime-versions:
            nodejs: latest
        commands:
            - echo "npm install -g serverless"
    pre_build:
        commands:
            - echo "npm install"
    build:
        commands:
            - echo "we are in the build block"
            - echo "we will run some tests"
    post_build:
        commands:
            - echo "we are in the post build phase"
