version: 0.2

phases:
    install:
        runtime-versions:
            nodejs: latest
        commands:
            - npm install -g serverless
            - sls -v
    pre_build:
        commands:
            - npm install
    build:
        commands:
            - echo "we are in the build block"
            - echo "we will run some tests"
    post_build:
        commands:
            - echo "we are in the post build phase"
