version: 0.2

phases:
    install:
        runtime-versions:
            nodejs: latest
        commands:
            - npm install -g serverless
            - sls -v
    pre_build:
        commands:
            - npm install
    build:
        commands:
            - sls package --verbose
    post_build:
        commands:
            - echo "we are in the post build phase!"
