Resources:
    ListProcessingRole:
        Type: AWS::IAM::Role
        Properties:
            Path: /
            RoleName: ${self:custom.resourceName}_list_processing
            AssumeRolePolicyDocument:
                Version: "2012-10-17"
                Statement:
                    - Effect: Allow
                      Principal:
                          Service:
                              - lambda.amazonaws.com
                      Action: sts:AssumeRole
            Policies:
                - PolicyName: ${self:custom.resourceName}_list_processing
                  PolicyDocument:
                      Version: "2012-10-17"
                      Statement:
                          # batch write into DynamoDB
                          - Effect: Allow
                            Action:
                                - dynamodb:GetItem
                                - dynamodb:UpdateItem
                                - dynamodb:Query
                                - dynamodb:BatchWriteItem
                            Resource:
                                - !GetAtt Table.Arn
                                - !Join
                                  - ""
                                  - - !GetAtt Table.Arn
                                    - "/index/*"
                          # allow S3 read data
                          - Effect: Allow
                            Action:
                                - s3:GetObject
                                - s3:PutObject
                            Resource:
                                - !GetAtt ListProcessingBucket.Arn
                                - !Join
                                  - ""
                                  - - !GetAtt ListProcessingBucket.Arn
                                    - "/*"

                          # allow to create eventbridge rules
                          - Effect: Allow
                            Action:
                                - events:PutRule
                                - events:DeleteRule
                                - events:PutTargets
                                - events:RemoveTargets
                            Resource: "*"

                          # allow SNS message send on mx/smtp validation end
                          - Effect: Allow
                            Action:
                                - sns:Publish
                            Resource:
                                - !Ref ListValidationEndTopic
                                - !Ref ListProcessingEndTopic

                          # allow cloudwatch
                          - Effect: Allow
                            Action:
                                - logs:CreateLogGroup
                                - logs:CreateLogStream
                                - logs:PutLogEvents
                            Resource: "*"
                          # xray
                          - Effect: Allow
                            Action:
                                - xray:PutTelemetryRecords
                                - xray:PutTraceSegments
                            Resource: "*"
