Transform: "AWS::LanguageExtensions"
Resources:
    ProcessListsStepFunction:
        Type: AWS::StepFunctions::StateMachine
        Properties:
            StateMachineName: ${self:custom.resourceName}_process_lists
            RoleArn: !GetAtt ProcessListsRole.Arn
            DefinitionSubstitutions:
                ListProcessingStartTopic: !Ref ListProcessingStartTopic
                ListProcessingEndTopic: !Ref ListProcessingEndTopic
                # note the LambdaFunction.Arn suffix and CamelCase notation of lambda function ref name
                ListPrevalidateFunction: !GetAtt ListPrevalidateLambdaFunction.Arn
                ListDomainsPreflightFunction: !GetAtt ListDomainsPreflightLambdaFunction.Arn
                ListMXCheckFunction: !GetAtt ListMXCheckLambdaFunction.Arn
                ListBundleResultsFunction: !GetAtt ListBundleResultsLambdaFunction.Arn
            DefinitionString: ${file(backend/step_functions/process_list/steps.js)}
