Resources:
    # user pool
    UserPool:
        Type: AWS::Cognito::UserPool
        Properties:
            UserPoolName: ${self:custom.resourceName}
            AutoVerifiedAttributes:
                - email
            UsernameAttributes:
                - email
            Schema:
                - Name: email
                  AttributeDataType: String
                  Mutable: true
                - Name: name
                  AttributeDataType: String
                  Mutable: true
            LambdaConfig:
                PreSignUp: !GetAtt CognitoPreSignupLambdaFunction.Arn
                PostAuthentication: !GetAtt CognitoPostAuthLambdaFunction.Arn
                CreateAuthChallenge: !GetAtt CognitoCreateChallengeLambdaFunction.Arn
                VerifyAuthChallengeResponse: !GetAtt CognitoVerifyChallengeLambdaFunction.Arn
                DefineAuthChallenge: !GetAtt CognitoDefineChallengeLambdaFunction.Arn
    # create the cognito pool client
    UserPoolClient:
        Type: AWS::Cognito::UserPoolClient
        Properties:
            ClientName: ${self:custom.resourceName}
            PreventUserExistenceErrors: ENABLED
            UserPoolId: !Ref UserPool
            ExplicitAuthFlows:
                - ALLOW_REFRESH_TOKEN_AUTH
                - ALLOW_CUSTOM_AUTH
    # create the identity pool
    IdentityPool:
        Type: AWS::Cognito::IdentityPool
        Properties:
            IdentityPoolName: ${self:custom.resourceName}
            AllowUnauthenticatedIdentities: false
            CognitoIdentityProviders:
                - ClientId: !Ref UserPoolClient
                  ProviderName: !GetAtt UserPool.ProviderName

    # Cognito Authorized Role
    CognitoAuthorizedRole:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument:
                Version: "2012-10-17"
                Statement:
                    - Effect: Allow
                      Principal:
                          Federated: cognito-identity.amazonaws.com
                      Action:
                          - sts:AssumeRoleWithWebIdentity
                      Condition:
                          StringEquals:
                              "cognito-identity.amazonaws.com:aud": !Ref IdentityPool
                          ForAnyValue:StringLike:
                              "cognito-identity.amazonaws.com:amr": authenticated
            Policies:
                - PolicyName: CognitoAuthorizedPolicy
                  PolicyDocument:
                      Version: "2012-10-17"
                      Statement:
                          - Effect: "Allow"
                            Action:
                                - mobileanalytics:PutEvents
                                - cognito-sync:*
                                - cognito-identity:*
                            Resource: "*"

    # presignup permission to invoke lambda
    CognitoPreSignupPermission:
        Type: AWS::Lambda::Permission
        Properties:
            Action: lambda:InvokeFunction
            Principal: cognito-idp.amazonaws.com
            SourceArn: !GetAtt UserPool.Arn
            FunctionName: !GetAtt CognitoPreSignupLambdaFunction.Arn
    # postauth permission to invoke lambda
    CognitoPostAuthPermission:
        Type: AWS::Lambda::Permission
        Properties:
            Action: lambda:InvokeFunction
            Principal: cognito-idp.amazonaws.com
            SourceArn: !GetAtt UserPool.Arn
            FunctionName: !GetAtt CognitoPostAuthLambdaFunction.Arn
    # create challenge
    CognitoCreateChallengePermission:
        Type: AWS::Lambda::Permission
        Properties:
            Action: lambda:InvokeFunction
            Principal: cognito-idp.amazonaws.com
            SourceArn: !GetAtt UserPool.Arn
            FunctionName: !GetAtt CognitoCreateChallengeLambdaFunction.Arn
    # verify challenge
    CognitoVerifyChallengePermission:
        Type: AWS::Lambda::Permission
        Properties:
            Action: lambda:InvokeFunction
            Principal: cognito-idp.amazonaws.com
            SourceArn: !GetAtt UserPool.Arn
            FunctionName: !GetAtt CognitoVerifyChallengeLambdaFunction.Arn
    # verify challenge
    CognitoDefineChallengePermission:
        Type: AWS::Lambda::Permission
        Properties:
            Action: lambda:InvokeFunction
            Principal: cognito-idp.amazonaws.com
            SourceArn: !GetAtt UserPool.Arn
            FunctionName: !GetAtt CognitoDefineChallengeLambdaFunction.Arn
