Resources:
    # list smtp validation done
    ListValidationEndTopic:
        Type: AWS::SNS::Topic
        Properties:
            TopicName: ${self:custom.resourceName}_validation_end
    # allow topic to invoke lambda
    ListValidationEndTopicLambdaInvokePermission:
        Type: AWS::Lambda::Permission
        Properties:
            Action: lambda:InvokeFunction
            Principal: sns.amazonaws.com
            SourceArn: !Ref ListValidationEndTopic
            FunctionName: !GetAtt ListBundleResultsLambdaFunction.Arn
    # subscribe lambda to topic
    ListValidationEndTopicSubscription:
        Type: AWS::SNS::Subscription
        Properties:
            Endpoint: !GetAtt ListBundleResultsLambdaFunction.Arn
            Protocol: lambda
            TopicArn: !Ref ListValidationEndTopic
    # list processing done
    ListProcessingEndTopic:
        Type: AWS::SNS::Topic
        Properties:
            TopicName: ${self:custom.resourceName}_processing_end
    # allow topic to invoke lambda
    ListProcessingEndTopicLambdaInvokePermission:
        Type: AWS::Lambda::Permission
        Properties:
            Action: lambda:InvokeFunction
            Principal: sns.amazonaws.com
            SourceArn: !Ref ListProcessingEndTopic
            FunctionName: !GetAtt ListProcessingFinishedLambdaFunction.Arn
    # subscribe lambda to topic
    ListProcessingEndTopicSubscription:
        Type: AWS::SNS::Subscription
        Properties:
            Endpoint: !GetAtt ListProcessingFinishedLambdaFunction.Arn
            Protocol: lambda
            TopicArn: !Ref ListProcessingEndTopic
    # list processing done
    SESFeedbackTopic:
        Type: AWS::SNS::Topic
        Properties:
            TopicName: ${self:custom.resourceName}_ses_feedback
    # subscribe lambda to topic
    SESFeedbackTopicSubscription:
        Type: AWS::SNS::Subscription
        Properties:
            Endpoint: !GetAtt ListProcessingFinishedLambdaFunction.Arn
            Protocol: lambda
            TopicArn: !Ref SESFeedbackTopic
