Resources:
    Queue:
        Type: AWS::SQS::Queue
        Properties:
            QueueName: ${self:custom.resourceName}
            VisibilityTimeout: 120
            RedrivePolicy:
                deadLetterTargetArn: !GetAtt QueueDLQ.Arn
                maxReceiveCount: 5
    QueueDLQ:
        Type: AWS::SQS::Queue
        Properties:
            QueueName: ${self:custom.resourceName}_DLQ
