Resources:
    # stream consumer role
    StreamConsumerRole:
        Type: AWS::IAM::Role
        Properties:
            Path: /
            RoleName: ${self:custom.resourceName}_stream_consumer
            AssumeRolePolicyDocument:
                Version: "2012-10-17"
                Statement:
                    - Effect: Allow
                      Principal:
                          Service:
                              - lambda.amazonaws.com
                      Action: sts:AssumeRole
            Policies:
                - PolicyName: ${self:custom.resourceName}_stream_consumer
                  PolicyDocument:
                      Version: "2012-10-17"
                      Statement:
                          # DynamoDB allow item update and stream related operations
                          - Effect: Allow
                            Action:
                                - dynamodb:Query
                                - dynamodb:UpdateItem
                                - dynamodb:DescribeStream
                                - dynamodb:GetRecords
                                - dynamodb:GetShardIterator
                                - dynamodb:ListShards
                                - dynamodb:ListStreams
                            Resource:
                                - !GetAtt Table.Arn
                                - !GetAtt Table.StreamArn
                                - !Join
                                  - ""
                                  - - !GetAtt Table.Arn
                                    - "/index/GSI"
                          # allow SQS message send
                          - Effect: Allow
                            Action:
                                - sqs:SendMessage
                            Resource:
                                - !GetAtt Queue.Arn
                          # allow SNS message send on mx/smtp validation end
                          - Effect: Allow
                            Action:
                                - sns:Publish
                            Resource:
                                - !Ref ListValidationEndTopic
                          # CW
                          - Effect: Allow
                            Action:
                                - logs:CreateLogGroup
                                - logs:CreateLogStream
                                - logs:PutLogEvents
                            Resource: "*"
                          # xray
                          - Effect: Allow
                            Action:
                                - xray:PutTelemetryRecords
                                - xray:PutTraceSegments
                            Resource: "*"
